version: '2'
name: app
services:
  web:
    restart: always
    container_name: app
    build: .
    ports:
      - 8000:5000
    volumes:
      - .:/app
    depends_on:
      - db
  
  db:
    image: postgres:latest
    container_name: db
    restart: always
    ports:
      - 5432:5432
    
    volumes:
      - ./data:/var/lib/postgresql/data

    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PWD}
      - POSTGRES_DB=${DB}